config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  root "homes#index"
  get "/" => "homes#index", as: :home
  get "homes/about" => "homes#about", as: :about_homes
  get "users/:id/mypage" => "users#mypage", as: :user_mypage
  devise_for :users
  resources :users
  resources :posts do
  	resources :post_comments, only: [:create, :destroy]
  	resource :likes, only: [:create, :destroy]
  	get :likes, on: :collection
  	get :prefectures, on: :collection
  end
  resources :prefectures, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id } # 一人のユーザーは一つの投稿に対して１いいねという制約
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :post_comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :tags, dependent: :destroy
	belongs_to :user
	belongs_to :prefecture
	attachment :post_image
	validates :is_valid, inclusion: { in: [true , false] }
	# 空白を制限
	validates :title, presence: true
	validates :address, presence: true
	validates :supplement, presence: true
	validates :text, presence: true
	validates :post_image, presence: true
# いいね機能のメソッド
	def like_by?(user)
		likes.where(user_id: user.id).exists?
	end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

	has_many :posts, dependent: :destroy 

# 全都道府県を記述。投稿に付属させるため
	enum trip: {北海道:0, 青森:1, 秋田:2, 岩手:3, 山形:4, 宮城:5, 福島:6, 群馬:7, 栃木:8, 茨城:9, 埼玉:10,
				東京:11, 千葉:12, 神奈川:13, 新潟:14, 富山:15, 石川:16, 福井:17, 長野:18, 山梨:19, 静岡:20,
				愛知:21, 岐阜:22, 滋賀:23, 三重:24, 京都:25, 大阪:26, 奈良:27, 和歌山:28, 兵庫:29, 鳥取:30,
				岡山:31, 島根:32, 広島:33, 山口:34, 香川:35, 徳島:36, 愛媛:37, 高知:38, 福岡:39, 佐賀:40,
				長崎:41, 熊本:42, 大分:43, 宮崎:44, 鹿児島:45, 沖縄:46}

end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :post
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
	belongs_to :tag
	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  attachment :profile_image
  # 空欄を制限
  validates :name, presence: true

# プロフィールに出身地の表示用
         enum local:{不明:0, 北海道:1, 青森:2, 秋田:3, 岩手:4, 山形:5, 宮城:6, 福島:7, 群馬:8, 栃木:9, 茨城:10, 埼玉:11, 東京:12, 千葉:13, 神奈川:14,
  			  新潟:15, 富山:16, 石川:17, 福井:18, 長野:19, 山梨:20, 静岡:21, 愛知:22, 岐阜:23, 滋賀:24, 三重:25, 京都:26, 大阪:27, 奈良:28, 
  			  和歌山:29, 兵庫:30, 鳥取:31, 岡山:32, 島根:33, 広島:34, 山口:35, 香川:36, 徳島:37, 愛媛:38, 高知:39, 福岡:40, 佐賀:41, 長崎:42,
  			  熊本:43, 大分:44, 宮崎:45, 鹿児島:46, 沖縄:47}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
# ログイン後にマイページへ遷移
	def after_sign_in_path_for(resouce)
		user_mypage_path(resouce)
	end
# ログアウト後にホムペーじへ遷移
	def after_sign_out_path_for(resouce)
		home_path
	end


protected
# 新規登録に名前を追加
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def about
	end
	def index
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
  	like = current_user.likes.build(post_id: params[:post_id])
  	like.save!
  	redirect_to post_path(params[:post_id])
  end

  def destroy
  	current_user.likes.find_by(post_id: params[:post_id]).destroy!
  	redirect_to post_path(params[:post_id])
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	def create
		post = Post.find(params[:post_id])
		comment = PostComment.new(post_comment_params)
		comment.user_id = current_user.id
		comment.post_id = post.id
		comment.save
		redirect_to post_path(post.id) 
	end

	def destroy
	    PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
	    redirect_to post_path(params[:post_id])
	end

private
	def post_comment_params
	    params.require(:post_comment).permit(:comment)
	end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    # 都道府県全てとそれぞれの県全てを分けて表示させる
  	if params[:prefecture_id]
  		# prefectureidを探す
  		@prefecture = Prefecture.find(params[:prefecture_id])
  	   # prefecture_idと紐づくデータを取得
	    @posts = @prefecture.posts.page(params[:page]).reverse_order
	else
	    # データをすべてを取得
	    @posts = Post.page(params[:page]).reverse_order
	end
  end

  def prefectures
  	@prefectures = Prefecture.all
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
  	if @post.save
      tags = Vision.get_image_data(@post.post_image)
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
  		redirect_to post_path(@post.id)
 	 else
 	 	render :new
 	 end
  end

  def show
  	@post = Post.find(params[:id])
  	@post_comment = PostComment.new
  end

  def likes
  	@like_posts = current_user.like_posts.page(params[:page]).per(200).order('updated_at DESC')
  end


private
    def post_params
        params.require(:post).permit(:title, :post_image, :is_valid, :address, :supplement, :text, :prefecture_id, :user_id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	# def show
 #    @tags = Tag.find(params[:id])
 #    @posts = @tags.posts.page(params[:page]).reverse_order
 #  end

def posts
    @tag = Tag.find(params[:id])
    @tag_posts = @tag.tag_posts.page(params[:page]).per(200).order('updated_at DESC')
  end

private
	def tag_params
		params.require(:tag).permit(:name)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@posts = @user.posts.page(params[:page]).per(200).order('updated_at DESC')
	end

	def edit
		@user = User.find(params[:id])
		if @user.id != current_user.id
  			redirect_to user_mypage_path(current_user.id)
  		end
	end

	def update
	  	@user = User.find(params[:id])
	  	if @user.update(user_params)
	  		redirect_to user_mypage_path(@user.id)
		else
		    render "edit"
		 end
  	end

 	def mypage
  	@user = User.find(params[:id])
  	@posts = @user.posts
	end

private

	def user_params
		params.require(:user).permit(:name, :profile_image, :local, :profile)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="container">
	<div class="box2 about-title">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center">Deep Local Trip とは</h1>
			</div>
		</div>
	</div>
	<div class="row well">
		<div class="col-md-12">
			<h3>Deep Local Tripは日本全国のおすすめを共有できるサイトです！旅行先のあのお店が美味しかったからみんなにおすすめしたい！や、地元のここの景色がとても綺麗だから是非見に行って欲しい！等の情報を専門にしたサイトです。旅行先を調べる時や、地元のご飯屋さんを調べたい時にも使えます！個人の投稿なのでネットの記事では出てこないディープな記事も見られるのが特徴です！<h3>
		</div>
	</div>
	<div class="box2 about-title">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center">Deep Local Trip 4つの魅力</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-3 col-md-12 box2 about-tizu">
			<%= image_tag asset_path('about1.png') %>
			<h2 class="box7 font-about">都道府県別で検索できる!</h2>
			<p>・都道府県別で投稿、検索できるので記事が探しやすいです！</p>
		</div>
		<div class="col-lg-3 col-md-12 box2 about-tizu">
			<%= image_tag asset_path('about2.png') %>
			<h2 class="box7 font-about">地元、旅行先を投稿できる!</h2>
			<p>・地元か旅行者かを分けて投稿できるので、調べてる時の判断材料になります！</p>
		</div>
		<div class="col-lg-3 col-md-12 box2 about-tizu">
			<%= image_tag asset_path('about3.png') %>
			<h2 class="box7 font-about">投稿に地図が出る!&emsp;&emsp;&emsp;</h2>
			<p>・投稿に地図が表示されるので、場所を明確にできます！</p>
		</div>
		<div class="col-lg-3 col-md-12 box2 about-tizu">
			<%= image_tag asset_path('heart_small.png') %>
			<h2 class="box7 font-about">ブックマーク機能がある！</h2>
			<p>・いいね機能でブックマークができます！マイページからお気に入り一覧が見れます！</p>
		</div>
	</div>
	<div class="box2 about-title">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center">使い方</h1>
			</div>
		</div>
		<div class="row about-post well">
			<div class="col-md-12">
				<%= image_tag asset_path('about_nav2.png'), size: "800x100", class: "center-block img" %>
				<h2>・まずは上の新規登録から会員登録をお願いします</h2>
				<%= image_tag asset_path('about_nav.png'), size: "800x100", class: "center-block img" %>
				<h2>・次に新規投稿を押して入力します(ログイン後上のリンクが変わります)</h2>
				<%= image_tag asset_path('about_newpost.png'), size: "800x800", class: "center-block img" %>
				<h2>・項目を全部埋めて投稿するを押したら投稿できます！</h2>	
				<%= image_tag asset_path('about_nav3.png'), size: "800x100", class: "center-block img" %>
				<h2>・記事を探すときは都道府県一覧から探してみてください！</h2>
				<h1 class="box7">早速使ってみよう！</h1>
			</div>
		</div>
	</div>
	
</div>

app/views/homes/index.html.erb
<div id="container">
        <div id="theTarget">
            <div style="background-image: url(<%= asset_path('home1.jpg') %>)"><h1 class="mv-title">Deep Local Trip</h1></div>
            <div style="background-image: url(<%= asset_path('home2.jpg') %>)"><h1 class="mv-title">Deep Local Trip</h1></div>
            <div style="background-image: url(<%= asset_path('home3.jpeg') %>)"><h1 class="mv-title">Deep Local Trip</h1></div>
            <div style="background-image: url(<%= asset_path('home4.jpg') %>)"><h1 class="mv-title">Deep Local Trip</h1></div>
            <div style="background-image: url(<%= asset_path('home5.jpeg') %>)"><h1 class="mv-title">Deep Local Trip</h1></div>
            <div style="background-image: url(<%= asset_path('home6.jpeg') %>)"><h1 class="mv-title">Deep Local Trip</h1></div>
            <div style="background-image: url(<%= asset_path('home7.jpeg') %>)"><h1 class="mv-title">Deep Local Trip</h1></div>
        </div>
</div>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<h1 class="col-md-offset-1"><%= (@prefecture.present?)? "#{@prefecture.name}一覧" : "全国一覧" %></h1>
			<% @posts.each do |post| %>
			  <div class="col-sm-12 col-md-6 waku">
			  	<!-- cardで表示 -->
			    <div class="card img-thumbnail">
			    	<%= link_to post_path(post.id) do %>
			      		<%= attachment_image_tag post, :post_image, :fill,500,500, format: 'jpeg', fallback: "show_image.png", class: "img" %>
			      	<% end %>
			      <div class="card-body">
			        <h2 class="card-title">
			        	<%= link_to user_mypage_path(post.user_id) do %>
			        		<%= attachment_image_tag post.user, :profile_image, :fill,70,70, format: 'jpeg', fallback: "show_image.png", class: 'img-circle' %>
			        	<% end %>
			        	&ensp;
			        	<%= link_to post.title, post_path(post.id) %>
			        </h2>
			        	<div class="card-text">
			        		<%= link_to user_mypage_path(post.user_id) do %>
			        			<p><%= post.user.name%></p>
			        		<% end %>
			        	</div>
			      </div>
			    </div>
			  </div>
			<% end %>
			<div class="row">
				<div class="col-lg-12">
					<%= paginate @posts %>
				</div>
			</div>
	</div>
</div>
<!-- フッター -->
<footer class="footer">
    <div class="container">
	    <h5 class="text-right text-muted">
            <a href="https://twitter.com/UtaAoba" target="_blank">
              <i class="fab fa-twitter-square"></i>
            </a>:作成者:さとう。
        </h5>
    </div>
</footer>
<!-- フッター -->

app/views/posts/likes.html.erb
<div class="container">
	<div class="row">
		<h1 class="col-md-offset-1">お気に入り</h1>
			<% @like_posts.each do |post| %>
			  <div class="col-sm-12 col-md-6 waku">
			    <div class="card img-thumbnail">
			    	<%= link_to post_path(post.id) do %>
			      		<%= attachment_image_tag post, :post_image, :fill,500,500, format: 'jpeg', fallback: "show_image.png", class: "img" %>
			      	<% end %>
			      <div class="card-body">
			        <h2 class="card-title">
			        	<%= link_to user_mypage_path(post.user_id) do %>
			        		<%= attachment_image_tag post.user, :profile_image, :fill,70,70, format: 'jpeg', fallback: "show_image.png", class: 'img-circle' %>
			        	<% end %>
			        	&ensp;
			        	<%= link_to post.title, post_path(post.id) %>
			        </h2>
			        	<div class="card-text">
			        		<%= link_to user_mypage_path(post.user_id) do %>
			        			<p><%= post.user.name%></p>
			        		<% end %>
			        	</div>
			      </div>
			    </div>
			  </div>
			<% end %>
	</div>
</div>
<!-- フッター -->
<footer class="footer">
    <div class="container">
	    <h5 class="text-right text-muted">
            <a href="https://twitter.com/UtaAoba" target="_blank">
              <i class="fab fa-twitter-square"></i>
            </a>:作成者:さとう。
        </h5>
    </div>
</footer>
<!-- フッター -->

app/views/posts/new.html.erb
 <div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <% if @post.errors.any? %>
                <div class="col-xs-12" id="error_explanation">
                    <h2>
                        <%= @post.errors.count %>件のエラーがあります</h2>
                    <ul>
                        <% @post.errors.full_messages.each do |m| %>
                        <li><%= m %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
              <div class="text-center">
                 <h2>新規投稿</h2>
             </div>
              <div class="form-body">
                  <%= form_for(@post) do |f| %>
                      <div class="field">
                          <label for="title">タイトル</label>
                          <%= f.text_field :title, size: "50*10" %>
                      </div>
                      <div class="field">
                          <br/><label for="is_valid">旅行先か地元かを選ぶ</label>
                          <%= f.select :is_valid, [["旅行客", true],["地元", false]] %>
                      </div>
                      <div class="field">
                          <br/><label for="prefecture">都道府県を選ぶ</label>
                          <%= f.collection_select :prefecture_id, Prefecture.all , :id, :name, include_blank: "" %>
                      </div>
                      <div class="field">
                          <br/><label for="address">場所の名前(GoogleMapがでます)</label>
                          <%= f.text_field :address, size: "50*10" %>
                      </div>
                      <div class="field">
                         <br/> <label for="supplement">補足事項(:駅の裏、飲食店等なんでもあり)</label>
                          <%= f.text_field :supplement, size: "50*10" %>
                      </div>
                      <div class="field">
                          <br/><label for="post_image">画像(必ず画像を入れてください)</label>
                          <%= f.attachment_field :post_image, placeholder: "画像" %>
                      </div>
                      <div class="field">
                          <br/><label for="text">本文</label>
                          <%= f.text_area :text, size: "50x10" %>
                      </div>
                      <div class="actions">
                          <br/><%= f.submit "投稿する", class:"btn btn-primary btn-lg btn-block btn-base-1 mt-20" %><br/><br/><br/>
                      </div>
                  <% end %>
            </div>
        </div>
    </div>
</div>
<!-- フッター -->
<footer class="footer">
    <div class="container">
        <h5 class="text-right text-muted">
            <a href="https://twitter.com/UtaAoba" target="_blank">
              <i class="fab fa-twitter-square"></i>
            </a>:作成者:さとう。
        </h5>
    </div>
</footer>
<!-- フッター -->

app/views/posts/prefectures.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1 well-lg">
			<%= link_to "すべての投稿を見る", posts_path, class:"btn btn-info btn-lg btn-block" %>
		</div>
		<% @prefectures.each do |prefectures| %>
			<div class="col-md-6 col-xs-12 ">
				<%= link_to prefectures.name,posts_path(prefecture_id:prefectures.id) ,class:"btn btn-lg btn-block button-size" %>
			</div>
		<% end %>		
	</div>	
</div>
<!-- フッター -->
<footer class="footer">
    <div class="container">
	    <h5 class="text-right text-muted">
            <a href="https://twitter.com/UtaAoba" target="_blank">
              <i class="fab fa-twitter-square"></i>
            </a>:作成者:さとう。
        </h5>
    </div>
</footer>
<!-- フッター -->

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<%= attachment_image_tag @post, :post_image, :fill, 1200, 900, format: 'jpeg', fallback: "show_image.png", class: "img" %>
		<div class="col-md-12">
			<h4>
				<% @post.tags.each do |tag| %>
	                <span class="label label-info"><%= tag.name %></span>
	              <% end %>
          	</h4>
			<h1 class="title-font box3">
				<%= @post.title %>
				<p class="text-right">
					<% if @post.like_by?(current_user) %>
						<%= link_to post_likes_path(@post), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							<%= @post.likes.count %>
						<% end %>
					<% else %>
						<%= link_to post_likes_path(@post), method: :post do %>
							<i class="fa fa-heart" aria-hidden="true" style="color: black;"></i>
							<%= @post.likes.count %>
						<% end %>
					<% end %>
				</p>
			</h1>
			<div class="row">
				<div class="pull-left">
					<%= link_to user_mypage_path(@post.user_id) do %>
						<%= attachment_image_tag @post.user, :profile_image, :fill, 200, 200, format: 'jpeg', fallback: "show_image.png", class: "img-circle" %> 
						<h3 class="space"><%= @post.user.name %></h3>
					<% end %>
				</div>
				<div class="center-block">
					<h2 class="post-under">場所の名前</h2>
					<h3 class="post-under"><%= @post.address %></h3>
					<h4 class="post-sub"><%= (@post.is_valid == true) ? "旅行先" : "地元" %>&ensp;:&ensp;<%= @post.prefecture.name %>について紹介</h4>
					<h3 class="post-under">補足事項</h3>
					<h4 class="post-sub"><%= @post.supplement %></h4>
					
				</div>
			</div>
			<!-- googlemapを表示 -->
			<div class="row">
				<h2 class="box1">地図(更新をクリック！)</h2>

				<!-- 地名入力用のinputを追加 -->
				<input id="address" type="textbox" value="<%= @post.address %>">

				<!-- buttonをクリックしたらcodeAddressを実行　-->
				<input type="button" value="更新" onclick="codeAddress()">
				<div id='map'>
				</div>

				<script>


				let map
				let geocoder

				function initMap(){
				  // geocoderを初期化
				  geocoder = new google.maps.Geocoder()

				  map = new google.maps.Map(document.getElementById('map'), {
				  center: {lat: 35.6812879, lng: 139.7670561},
				  zoom: 15
				  });
				}

				function codeAddress(){
				  // 入力を取得
				  let inputAddress = document.getElementById('address').value;

				  // geocodingしたあとmapを移動
				  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
				    if (status == 'OK') {
				　　　　　　　　　　　　// map.setCenterで地図が移動
				      map.setCenter(results[0].geometry.location);

				　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
				      var marker = new google.maps.Marker({
				          map: map,
				          position: results[0].geometry.location
				      });
				    } else {
				      alert('Geocode was not successful for the following reason: ' + status);
				    }
				  });
				}

				</script>
				<!-- detenv-rails でAPIkeyを隠す -->
				<script src="https://maps.googleapis.com/maps/api/js?key= <%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
			</div>

			<div class="row">
				<h1 class="box1">本文</h1>
				<div class="panel">
					<h2><%= @post.text %></h2>
				</div>
			</div>
			<div class="row">
				<h1 class="box1">コメント一覧</h1>
				<div class="well">
				<h3><i class="fa fa-comment"></i>&ensp;<%= @post.post_comments.count %>件のコメント</h3>
				<ol>
				    <% @post.post_comments.each do |post_comment| %>
				        <li>
				        	<div>
					       		<p class="comment-left"><%= post_comment.user.name %></p>
					       		<p class="comment-right"><%= post_comment.created_at.to_s(:datetime_jp) %></p>
					        </div>
					        <div class="comment-under">
					        	<%= link_to user_mypage_path(post_comment.user_id) do %>
								<%= attachment_image_tag post_comment.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "comment_image.png", class: "img-circle" %> 
								<% end %>
					            <%= post_comment.comment %>
					            <% if post_comment.user == current_user%>
								<%= link_to "コメントを削除する", post_post_comment_path(post_comment.post, post_comment), method: :delete, class: "text-danger pull-right" %><br/><br/>
								<% end %>
							</div>
				        </li>
				    <% end %>
				</ol>
				<%= form_for [@post, @post_comment] do |f| %>
				    <div class="row">
				        <div class="col-sm-12">
				            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメント" %>
				        </div>
				    </div>
				    <div class="row post-bt">
					 <%= f.submit "送信する", class: "btn btn-lg btn-info pull-right" %>
					</div>
				<% end %>
			</div>
		</div>
		</div>
	</div>
</div>
<!-- フッター -->
<footer class="footer">
    <div class="container">
	    <h5 class="text-right text-muted">
            <a href="https://twitter.com/UtaAoba" target="_blank">
              <i class="fab fa-twitter-square"></i>
            </a>:作成者:さとう。
        </h5>
    </div>
</footer>
<!-- フッター -->

app/views/users/mypage.html.erb
<div class="container">
	<h2>マイページ</h2>
	<div class="row">
		<div class="col-md-12">
			<!-- プロフィール -->
			<div class="pull-left mypage-top">
				<%= attachment_image_tag @user, :profile_image, :fill, 300, 300, format: 'jpeg', fallback: "mypage_image.png" , class: "img"%>
			</div>
			<div class="center-block mypage-top">
				<h2 class="mypage-under">ニックネーム</h2>
				<h3 class="mypage-text"><%= @user.name %></h3><!-- ニックネームの表示 -->
				<h2 class="mypage-under">出身地</h2>
				<h3 class="mypage-text"><%= @user.local %></h3><!-- 出身地を表示 -->
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 mypage-top">
			<h2 class="">プロフィール</h2>
			<div class="panel">
					<h3 class=""><%= @user.profile%></h3><!-- 本文を表示 -->
			</div>
			<% if @user == current_user %><!-- ログインユーザーのみ -->
				<%= link_to '編集する', edit_user_path(current_user.id), class: 'col-md-3 col-md-offset-9 btn btn-default' %>
			<% else %>
			<% end %>
		</div>
	</div>
			<!-- プロフィール終了 -->
	<div class="row">
		<div class="col-md-12 col-xs-12 mypage-top">
				<h2>投稿</h2>
				<% if @user == current_user %> <!-- ログインユーザーのみ。他人のマイページの時はその人の投稿を表示 -->
					<%= link_to '自分の投稿', user_path(current_user.id), class: 'btn btn-lg btn-block button-size' %>
					<%= link_to 'お気に入り一覧', likes_posts_path, class: 'btn btn-lg btn-block button-size' %>
				<% else %>
					<%= link_to user_path(@user.id) do%>
						<p class="btn btn-lg btn-block button-size"><%= @user.name %>の投稿を見る</p> 
					<% end %>
				<% end %>
		</div>
	</div>
</div>
<!-- フッター -->
<footer class="footer">
    <div class="container">
	    <h5 class="text-right text-muted">
            <a href="https://twitter.com/UtaAoba" target="_blank">
              <i class="fab fa-twitter-square"></i>
            </a>:作成者:さとう。
        </h5>
    </div>
</footer>
<!-- フッター -->