config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  root "homes#index"
  get "/" => "homes#index", as: :home
  get "homes/about" => "homes#about", as: :about_homes
  get "users/:id/mypage" => "users#mypage", as: :user_mypage
  devise_for :users
  resources :users
  resources :posts do
  	resources :post_comments, only: [:create, :destroy]
  	resource :likes, only: [:create, :destroy]
  	get :likes, on: :collection
  	get :prefectures, on: :collection
  end
  resources :prefectures, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id } # 一人のユーザーは一つの投稿に対して１いいねという制約
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :post_comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :tags, dependent: :destroy
	belongs_to :user
	belongs_to :prefecture
	attachment :post_image
	validates :is_valid, inclusion: { in: [true , false] }
	# 空白を制限
	validates :title, presence: true
	validates :address, presence: true
	validates :supplement, presence: true
	validates :text, presence: true
	validates :post_image, presence: true
# いいね機能のメソッド
	def like_by?(user)
		likes.where(user_id: user.id).exists?
	end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

	has_many :posts, dependent: :destroy 

# 全都道府県を記述。投稿に付属させるため
	enum trip: {北海道:0, 青森:1, 秋田:2, 岩手:3, 山形:4, 宮城:5, 福島:6, 群馬:7, 栃木:8, 茨城:9, 埼玉:10,
				東京:11, 千葉:12, 神奈川:13, 新潟:14, 富山:15, 石川:16, 福井:17, 長野:18, 山梨:19, 静岡:20,
				愛知:21, 岐阜:22, 滋賀:23, 三重:24, 京都:25, 大阪:26, 奈良:27, 和歌山:28, 兵庫:29, 鳥取:30,
				岡山:31, 島根:32, 広島:33, 山口:34, 香川:35, 徳島:36, 愛媛:37, 高知:38, 福岡:39, 佐賀:40,
				長崎:41, 熊本:42, 大分:43, 宮崎:44, 鹿児島:45, 沖縄:46}

end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :post
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
	belongs_to :tag
	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  attachment :profile_image
  # 空欄を制限
  validates :name, presence: true

# プロフィールに出身地の表示用
         enum local:{不明:0, 北海道:1, 青森:2, 秋田:3, 岩手:4, 山形:5, 宮城:6, 福島:7, 群馬:8, 栃木:9, 茨城:10, 埼玉:11, 東京:12, 千葉:13, 神奈川:14,
  			  新潟:15, 富山:16, 石川:17, 福井:18, 長野:19, 山梨:20, 静岡:21, 愛知:22, 岐阜:23, 滋賀:24, 三重:25, 京都:26, 大阪:27, 奈良:28, 
  			  和歌山:29, 兵庫:30, 鳥取:31, 岡山:32, 島根:33, 広島:34, 山口:35, 香川:36, 徳島:37, 愛媛:38, 高知:39, 福岡:40, 佐賀:41, 長崎:42,
  			  熊本:43, 大分:44, 宮崎:45, 鹿児島:46, 沖縄:47}

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def about
	end
	def index
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
  	like = current_user.likes.build(post_id: params[:post_id])
  	like.save!
  	redirect_to post_path(params[:post_id])
  end

  def destroy
  	current_user.likes.find_by(post_id: params[:post_id]).destroy!
  	redirect_to post_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    # 都道府県全てとそれぞれの県全てを分けて表示させる
  	if params[:prefecture_id]
  		# prefectureidを探す
  		@prefecture = Prefecture.find(params[:prefecture_id])
  	   # prefecture_idと紐づくデータを取得
	    @posts = @prefecture.posts.page(params[:page]).reverse_order
	else
	    # データをすべてを取得
	    @posts = Post.page(params[:page]).reverse_order
	end
  end

  def prefectures
  	@prefectures = Prefecture.all
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
  	if @post.save
      tags = Vision.get_image_data(@post.post_image)
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
  		redirect_to post_path(@post.id)
 	 else
 	 	render :new
 	 end
  end

  def show
  	@post = Post.find(params[:id])
  	@post_comment = PostComment.new
  end

  def likes
  	@like_posts = current_user.like_posts.page(params[:page]).per(200).order('updated_at DESC')
  end


private
    def post_params
        params.require(:post).permit(:title, :post_image, :is_valid, :address, :supplement, :text, :prefecture_id, :user_id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	# def show
 #    @tags = Tag.find(params[:id])
 #    @posts = @tags.posts.page(params[:page]).reverse_order
 #  end

def posts
    @tag = Tag.find(params[:id])
    @tag_posts = @tag.tag_posts.page(params[:page]).per(200).order('updated_at DESC')
  end

private
	def tag_params
		params.require(:tag).permit(:name)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@posts = @user.posts.page(params[:page]).per(200).order('updated_at DESC')
	end

	def edit
		@user = User.find(params[:id])
		if @user.id != current_user.id
  			redirect_to user_mypage_path(current_user.id)
  		end
	end

	def update
	  	@user = User.find(params[:id])
	  	if @user.update(user_params)
	  		redirect_to user_mypage_path(@user.id)
		else
		    render "edit"
		 end
  	end

 	def mypage
  	@user = User.find(params[:id])
  	@posts = @user.posts
	end

private

	def user_params
		params.require(:user).permit(:name, :profile_image, :local, :profile)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeepLocalTrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>        
      <header class="navbar navbar-expand-lg navbar-fixed-top" style="background-color:#F29A7E;">
        <div class="container">
          <nav class="nav navbar-nav navbar-left">
            <%= link_to (root_path) do %>
              <%= image_tag 'logo.png',:size =>'120x70' %>
            <% end %>
            <button class="navbar-toggler res pull-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替" style="background-color:#F29A7E;">
            <span class="navbar-toggler-icon">≡</span>
          </button>
          </nav>
          <nav class="collapse navbar-collapse" id="navbar">
            <ul class=" nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to 'ホーム', home_path, class: "glyphicon glyphicon-home" %></li>
                <li class="nav-item"><%= link_to "アバウト", about_homes_path, class: "glyphicon glyphicon-link" %></li>
                <li class="nav-item"><%= link_to '新規投稿', new_post_path, class: "glyphicon glyphicon-picture" %></li>
                <li class="nav-item"><%= link_to '都道府県一覧', prefectures_posts_path, class: "glyphicon glyphicon-globe" %></li>
                <li class="nav-item"><%= link_to 'マイページ', user_mypage_path(current_user.id), class: "glyphicon glyphicon-user" %></li>
                <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %></li>
              <% else %>
                <li class="nav-item"><%= link_to 'ホーム', root_path, class: "glyphicon glyphicon-home" %></li>
                <li class="nav-item"><%= link_to "アバウト", about_homes_path, class: "glyphicon glyphicon-link" %></li>
                <li class="nav-item"><%= link_to "新規登録", new_user_registration_path,class: "glyphicon glyphicon-edit sign_up" %></li>
                <li class="nav-item"><%= link_to "ログイン", new_user_session_path,class: "glyphicon glyphicon-log-in sign_in" %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>
    <%= yield %>
  </body>
</html>